// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVd2BTmCXuGVHAdtoBhxgATiBnTD63zA',
    appId: '1:54729759940:web:88c6fda982b07157157d91',
    messagingSenderId: '54729759940',
    projectId: 'rosun-fi-windows',
    authDomain: 'rosun-fi-windows.firebaseapp.com',
    storageBucket: 'rosun-fi-windows.firebasestorage.app',
    measurementId: 'G-BFD84N6X2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ993E0PgsK60bh9BSxE9Bm5ZuGOdcVGI',
    appId: '1:54729759940:android:2b53cfee64f2cb72157d91',
    messagingSenderId: '54729759940',
    projectId: 'rosun-fi-windows',
    storageBucket: 'rosun-fi-windows.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSqbJA8iLRGnZoaMNBQCGPq-dt-qEakgU',
    appId: '1:54729759940:ios:07c669c7f10362bd157d91',
    messagingSenderId: '54729759940',
    projectId: 'rosun-fi-windows',
    storageBucket: 'rosun-fi-windows.firebasestorage.app',
    iosBundleId: 'com.example.rosunFiWindows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSqbJA8iLRGnZoaMNBQCGPq-dt-qEakgU',
    appId: '1:54729759940:ios:07c669c7f10362bd157d91',
    messagingSenderId: '54729759940',
    projectId: 'rosun-fi-windows',
    storageBucket: 'rosun-fi-windows.firebasestorage.app',
    iosBundleId: 'com.example.rosunFiWindows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIVd2BTmCXuGVHAdtoBhxgATiBnTD63zA',
    appId: '1:54729759940:web:871f40a2baea7b94157d91',
    messagingSenderId: '54729759940',
    projectId: 'rosun-fi-windows',
    authDomain: 'rosun-fi-windows.firebaseapp.com',
    storageBucket: 'rosun-fi-windows.firebasestorage.app',
    measurementId: 'G-VJZ9CLTZ5W',
  );

}